server:
  port: 9900
  servlet:
    context-path: /java/paper
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.104.231.221:3306/PAPER?allowMultiQueries=true&characterEncoding=utf8&useSSL=false&useAffectedRows=true&serverTimezone=UTC
    username: biye
    password: biye
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 200MB
mybatis:
  mapper-locations: classpath*:mapper/*.xml
  configuration:
    call-setters-on-nulls: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
